### PR TITLE
Adding support for innerPadding prop (GoogleMap.setPadding())

### PR DESCRIPTION
**Pull request by julianocomg**
Sometimes we need a padding inside the map container.
http://stackoverflow.com/questions/6923472/relocate-google-logo-in-mapview

### CODE REVIEW

**Comment by jrichardlai** [comment]
@julianocomg thanks for the PR, can you add an example and also add this prop to the documentation https://github.com/lelandrichardson/react-native-maps/blob/master/docs/mapview.md writing a note about it being only for Android ?

**Comment by julianocomg** [comment]
@jrichardlai Can you check now?

**Comment by jrichardlai** [comment]
@julianocomg sorry didn't checked it out yet will do tonight, but it seems that the example is not included in the main list of examples, can you add it at the bottom so we can navigate to it?

**Comment by julianocomg** [comment]
@jrichardlai done 👍  (I guess)

**Comment by jrichardlai** [comment]
@julianocomg can't run the example for some reason, does this work for you?

**Comment by julianocomg** [comment]
@jrichardlai I get this error: 

```
* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module AirMaps : Configuration with name 'default' not found.
```

But I don't know why '-'

**Comment by jrichardlai** [comment]
@julianocomg can you rebase master? The example project has been updated.

**Comment by julianocomg** [comment]
I did, and I still can't run your example app.

**Pull request closed without merging**
