### PR TITLE
Fix Circle overlay

### LINKED ISSUE #54: <MapView.Circle /> does not update its position when changing its center
I'm trying to put a circle in the center of my map. I have the following : 
```
<MapView.Circle
    center={{latitude: this.state.region.latitude, longitude: this.state.region.longitude}}
    radius=1000
    fillColor="rgba(0, 0, 0, 0.2)"
    strokeColor="rgba(0, 0, 0, 0.2)"/>
```
but the circle doesn't change when I change region while my MapView has a onRegionChange method that sets the new region 
```
onRegionChange = (region) => {
    this.setState({region: region});
}
```

### PR DESCRIPTION
**Pull request by CAPSLOCKUSER**
Fixes #54 

The Circle wasn't updating position, when center or radius props changed. There was a missing line in `AIRMap.m`.

### CODE REVIEW

**Comment by jrichardlai** [comment]
Thanks for the PR

**Comment by yonahforst** [comment]
my circles still don't update when the center changes. I thought this was a 'feature' of MKOverlays where you need to remove then re-add them to change their position. But it sounds like you have it working?

**Comment by NomadGraphix** [comment]
Hey, looks like this may not have gotten into the latest releases. I ended up having to reimplement it. In the latest version.

**Comment by rborn** [comment]
@NomadGraphix do you have a PR for it or?

**Comment by NomadGraphix** [comment]
I do not. :D But if you'd like I can make one.

**Comment by NomadGraphix** [comment]
@rborn https://github.com/react-community/react-native-maps/pull/2101

**Pull request merged**
