### PR TITLE
converted to RN 0.24+

### PR DESCRIPTION
**Pull request by jgibbons**

### CODE REVIEW

**Comment by christopherdro** [comment]
Is this backwards compatible with older versions of RN?

**Comment by jrichardlai** [comment]
Merging this as RN 0.26 is coming up

**Comment by christopherdro** [comment]
Please update the docs, preferably at the beginning of the README explaining this change and what versions of react native this will effect.

**Comment by jrichardlai** [comment]
Yep sounds good!

**Comment by christopherdro** [comment]
👍  Thank you.

**Comment by jrichardlai** [comment]
@christopherdro I did some test, and it seems that this actually work out of the box from [0.18](https://github.com/facebook/react-native/releases/tag/v0.18.0), which is when react was used from npm. But otherwise it would also work if react is added as a dependency to the project for version lower than 0.17. I will write a note about it.

**Comment by christopherdro** [comment]
That sounds great! We can add this to the 'Compatibility' section.

**Comment by scottluptowski** [comment]
@jrichardlai Thanks for this update!

Will `package.json` be updated to reflect this change? I am still getting a deprecation warning in my app because my `package.json` is pointing to 0.3.2, which according to Git was 3 weeks ago. I'd prefer for my app to track a version number instead of `master` of a git branch.

Thanks again

**Pull request merged**
