### PR TITLE
Added ability for caching map as static image

### PR DESCRIPTION
**Pull request by ivanfoong**
Added ability for caching map as static image for performance reason, also added loading indicator to be display while map is being cache.

New props; `cachedEnabled`, `loadingEnabled`, `loadingBackgroundColor`, `loadingIndicatorColor`

Big thanks to @jrichardlai for his contribution and guiding me on this commit.

Superseed #91

### CODE REVIEW

**Comment by jrichardlai** [comment]
Thanks @ivanfoong I'll try out more tomorrow but been using this on prod for a while now :)

**Comment by jrichardlai** [comment]
@ivanfoong I think we are missing something the drag does not work anymore for iOS

**Comment by jrichardlai** [comment]
@ivanfoong here is a diff of fix, the problem is that `setScrollEnabled` and `setZoomEnabled` should not be called explicitly unless the values have been set

```diff
diff --git a/ios/AirMaps/AIRMap.m b/ios/AirMaps/AIRMap.m
index 4c3e6f7..702fba9 100644
--- a/ios/AirMaps/AIRMap.m
+++ b/ios/AirMaps/AIRMap.m
@@ -32,8 +32,8 @@ const CGFloat AIRMapZoomBoundBuffer = 0.01;
 @interface AIRMap ()

 @property (nonatomic, strong) UIActivityIndicatorView *activityIndicatorView;
-@property (nonatomic, assign) BOOL shouldZoomEnabled;
-@property (nonatomic, assign) BOOL shouldScrollEnabled;
+@property (nonatomic, assign) NSNumber *shouldZoomEnabled;
+@property (nonatomic, assign) NSNumber *shouldScrollEnabled;

 - (void)updateScrollEnabled;
 - (void)updateZoomEnabled;
@@ -313,7 +313,7 @@ const CGFloat AIRMapZoomBoundBuffer = 0.01;
 }

 - (void)setScrollEnabled:(BOOL)scrollEnabled {
-    self.shouldScrollEnabled = scrollEnabled;
+    self.shouldScrollEnabled = [NSNumber numberWithBool:scrollEnabled];
     [self updateScrollEnabled];
 }

@@ -321,13 +321,13 @@ const CGFloat AIRMapZoomBoundBuffer = 0.01;
     if (self.cacheEnabled) {
         [super setScrollEnabled:NO];
     }
-    else {
-        [super setScrollEnabled:self.shouldScrollEnabled];
+    else if (self.shouldScrollEnabled != nil) {
+        [super setScrollEnabled:[self.shouldScrollEnabled boolValue]];
     }
 }

 - (void)setZoomEnabled:(BOOL)zoomEnabled {
-    self.shouldZoomEnabled = zoomEnabled;
+    self.shouldZoomEnabled = [NSNumber numberWithBool:zoomEnabled];
     [self updateZoomEnabled];
 }

@@ -335,8 +335,8 @@ const CGFloat AIRMapZoomBoundBuffer = 0.01;
     if (self.cacheEnabled) {
         [super setZoomEnabled: NO];
     }
-    else {
-        [super setZoomEnabled:self.shouldZoomEnabled];
+    else if (self.shouldZoomEnabled != nil) {
+        [super setZoomEnabled:[self.shouldZoomEnabled boolValue]];
     }
 }
```

**Comment by ivanfoong** [comment]
@jrichardlai thanks! I just test your fix works and pushed the bug fix commit

**Comment by jrichardlai** [comment]
👍 merging!

**Comment by npomfret** [comment]
Have a problem upgrade to 0.6.0.  I'm seeing this error:

`E/ReactNativeJS: `Constructor` has no propType for native prop `AIRMap.cacheEnabled` of native type `boolean`
                                                         If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.`

Any ideas?

**Comment by erickreutz** [comment]
Calling `fitToElements` with `cacheEnabled={true}` does nothing. Anyone else having problems?

**Comment by ivanfoong** [comment]
Hi @npomfret, try cleaning the project and build again, usually it's due to the IDE using the older builds for the library.

**Comment by ivanfoong** [comment]
Hi @erickreutz, sorry for the late reply. I have not used `fitToElements` before, but my guess now would be `fitToElements` needs additional code to `refresh` the cache upon completion, as cached image should be the image prior to calling `fitToElements`

**Comment by erickreutz** [comment]
No worries @ivanfoong. It's working for me on iOS but not Android.

**Comment by ninjz** [comment]
I tried using the `cacheEnabled` property set to true, and i'm just getting a loading indicator loading for a very long time with no map showing up

**Comment by npomfret** [comment]
Are there any docs on how to use caching?  I'm currently using google static maps to do static images of maps, but it'd would be preferable to use this project.

**Pull request merged**
