### PR TITLE
Corrected installation guide

### PR DESCRIPTION
**Pull request by AKovtunov**
Went step-by-step through all guide and found that without this line `import com.airbnb.android.react.maps.MapsPackage;` Java code will not work.
Also fixed small outdated lines

### CODE REVIEW

**Comment by AKovtunov** [comment]
Just found that someone has deleted that line from .java file in the previous commit. I can't find the reason for this. I have latest react native and it threw me some errors without it.

**Comment by Prims47** [comment]
:+1:

**Comment by christopherdro** [comment]
@AKovtunov Closing this for #235. I think everything in there includes in this PR.

**Comment by AKovtunov** [comment]
@christopherdro oh, haven't see that one :+1:

**Pull request closed without merging**
