### PR TITLE
Fix a few warnings on iOS

### PR DESCRIPTION
**Pull request by terribleben**

### CODE REVIEW

**Comment by spikebrehm** [comment]
Thanks! 🍻

**Comment by spikebrehm** [comment]
Just published [0.8.1](https://github.com/lelandrichardson/react-native-maps/releases/tag/v0.8.1) that includes this change.

**Comment by terribleben** [comment]
Really appreciate the quick response!

**Comment by spikebrehm** [comment]
It turns out 0.8.1 was faulty, because my working directory had an additional example app containing the `react-native` node module, which got published as part of the NPM package (:facepalm:), causing a `@providesModule` error, so I've unpublished it and published [0.8.2](https://github.com/lelandrichardson/react-native-maps/releases/tag/v0.8.2).  Use that instead!

**Pull request merged**
