### PR TITLE
Fix all remaining ESLint violations

### PR DESCRIPTION
**Pull request by spikebrehm**
Fix all remaining ESLint violations. Commits split up mostly by which linting rule addressed.

```
$ npm run -s lint
```

Next step, after this: set up Travis to automatically run linting on PRs.

cc: @lelandrichardson @christopherdro @jrichardlai

### CODE REVIEW

**Comment by spikebrehm** [comment]
I've also smoke-tested all the examples.

**Comment by jrichardlai** [comment]
Wow thanks! looks good

**Comment by gilbox** [comment]
lgtm

**Comment by jrichardlai** [comment]
I got `
react-native-maps/example/examples/AnimatedViews.js
  399:5  error  Expected exception block, space or tab after '//' in comment  spaced-comment
`

**Comment by spikebrehm** [comment]
> I got  `react-native-maps/example/examples/AnimatedViews.js 399:5 error Expected exception block, space or tab after '//' in comment spaced-comment`

That's worrisome, because I don't see than locally on `npm run lint`, O_o.

In any case, I fixed that and pushed.

**Comment by jrichardlai** [comment]
Strange, I'll double check if I have some settings set up somewhere

**Comment by spikebrehm** [comment]
Just published [0.8.1](https://github.com/lelandrichardson/react-native-maps/releases/tag/v0.8.1) that includes this change.

**Comment by spikebrehm** [comment]
It turns out 0.8.1 was faulty, because my working directory had an additional example app containing the `react-native` node module, which got published as part of the NPM package (:facepalm:), causing a `@providesModule` error, so I've unpublished it and published [0.8.2](https://github.com/lelandrichardson/react-native-maps/releases/tag/v0.8.2).  Use that instead!

**Pull request merged**
