### PR TITLE
Updates the example app to match recent changes

### PR DESCRIPTION
**Pull request by felipecsl**
* Fixes license
* Updates version to 0.4.1
* Update the example android app package and imports

### CODE REVIEW

**Comment by jrichardlai** [comment]
Thanks @felipecsl for updating the example. I tried to run it it didn't build for me for some reason.

`cd example`
`rm -rf node_modules`
`npm install`
`react-native run-android`

screen shot 2016-05-14 at 10 41 58 am

Also where is 0.25.1 coming from?

I changed `compile "com.facebook.react:react-native:0.25.1"` back to `compile "com.facebook.react:react-native:+"`

And also set it in the package.json to 0.24.1 to test it out 0.25.1 was still showing in the error.

**Comment by felipecsl** [comment]
@jrichardlai the problem is that you need to `npm install` in the project root directory as well.
This is because of the way the projects area set up right now, since the example app and the actual library code are in different locations, they look for the RN jar in different locations

**Comment by felipecsl** [comment]
Oh I think I missed one change here that might be causing this too, updating this PR in a bit

**Comment by felipecsl** [comment]
@jrichardlai can you try running `npm install` in the root project directory please? i can't reproduce this anymore, I think gradle might have cached RN somewhere on my environment

**Comment by felipecsl** [comment]
I've moved some of the changes here to a separate PR (#234). I'll rebase this one once that is landede

**Comment by jrichardlai** [comment]
@felipecsl i still get the same error, could you try to go to the example folder and update 0.25.1 by 0.24.1 and see if you can build the project properly 

```
diff --git a/example/android/app/build.gradle b/example/android/app/build.gradle
index 692e63d..7c59b3f 100644
--- a/example/android/app/build.gradle
+++ b/example/android/app/build.gradle
@@ -100,6 +100,6 @@ android {

 dependencies {
     compile "com.android.support:appcompat-v7:23.4.0"
-    compile "com.facebook.react:react-native:0.25.1"  // From node_modules
+    compile "com.facebook.react:react-native:0.24.1"  // From node_modules
     compile project(':react-native-maps')
 }
diff --git a/example/package.json b/example/package.json
index 3b4ca0c..6112dac 100644
--- a/example/package.json
+++ b/example/package.json
@@ -7,7 +7,7 @@
   },
   "dependencies": {
     "react": "^0.14.8",
-    "react-native": "^0.25.1",
+    "react-native": "^0.24.1",
     "react-native-maps": "../"
   }
 }
```

**Comment by jrichardlai** [comment]
@felipecsl investigated a little more had to make a change in `android/lib/build.gradle`

compile 'com.facebook.react:react-native:0.25.1' has to be changed to compile 'com.facebook.react:react-native:+'

```patch
diff --git a/android/lib/build.gradle b/android/lib/build.gradle
index 867416e..1a4908e 100644
--- a/android/lib/build.gradle
+++ b/android/lib/build.gradle
@@ -16,7 +16,7 @@ android {
 }

 dependencies {
-  compile 'com.facebook.react:react-native:0.25.1'
+  compile 'com.facebook.react:react-native:+'
   compile "com.google.android.gms:play-services-base:8.4.0"
   compile 'com.google.android.gms:play-services-maps:8.4.0'
 }
diff --git a/example/android/app/build.gradle b/example/android/app/build.gradle
index 692e63d..7c59b3f 100644
--- a/example/android/app/build.gradle
+++ b/example/android/app/build.gradle
@@ -100,6 +100,6 @@ android {

 dependencies {
     compile "com.android.support:appcompat-v7:23.4.0"
-    compile "com.facebook.react:react-native:0.25.1"  // From node_modules
+    compile "com.facebook.react:react-native:0.24.1"  // From node_modules
     compile project(':react-native-maps')
 }
diff --git a/example/package.json b/example/package.json
index 3b4ca0c..6112dac 100644
--- a/example/package.json
+++ b/example/package.json
@@ -7,7 +7,7 @@
   },
   "dependencies": {
     "react": "^0.14.8",
-    "react-native": "^0.25.1",
+    "react-native": "^0.24.1",
     "react-native-maps": "../"
   }
 }
```

**Comment by jrichardlai** [comment]
@felipecsl thoughts on this?

**Comment by jrichardlai** [comment]
Merging this so the example will run for Android

**Comment by felipecsl** [comment]
thanks @jrichardlai and sorry about the delay. Been busy the last couple days. I can help troubleshooting if it's still not working

**Pull request merged**
