### PR TITLE
add terrain map type

### PR DESCRIPTION
**Pull request by heydabop**

### CODE REVIEW

**Comment by lelandrichardson** [comment]
@heydabop is this google maps only? is there a mapkit equivalent?

**Comment by heydabop** [comment]
@lelandrichardson Oh, sorry, to my knowledge it's only Google Maps.

**Comment by christopherdro** [comment]
@heydabop What would show on iOS if the map type was set to terrain? 

Could you also update the code comments and doc file to show that its Android specific?

Thanks!

**Comment by heydabop** [comment]
@christopherdro I'm not sure I haven't tried. That being said if I try to set map to terrain in android and haven't applied this patch it crashes, IIRC. I can confirm this later, and change the documentation.

**Comment by christopherdro** [comment]
@heydabop :Thum

**Comment by heydabop** [comment]
Sorry, I cocked up my repo so I've had to make a new PR. [https://github.com/lelandrichardson/react-native-maps/pull/127](#127)

**Comment by MiLeung** [comment]
Anyone know when the terrain map type will be supported on iOS?

**Pull request closed without merging**
