### PR TITLE
Separate showing and following user

### PR DESCRIPTION
**Pull request by athaeryn**
As mentioned in #151, setting `showsUserLocation` also animates the map to the users location, but this is not always desired. To allow more control, I've added another property, `followsUserLocation`. This allows individual control of these two behaviors.

### CODE REVIEW

**Comment by christopherdro** [comment]
Thanks for the PR!

Is this a issue on Android as well?

If `followUserLocation` if for iOS only can you add `@platform ios` to the bottom of props comment.?

**Comment by athaeryn** [comment]
Not an issue on Android. I'll add the `@platform ios` line!

**Comment by christopherdro** [comment]
Thank you!

**Comment by AugustoAleGonZhipCode** [comment]
Do you have any idea how to do the followsUserLocation true works on Android? I have a problem with that.

**Pull request merged**
