### PR TITLE
Add pitchEnabled property to MapView

### PR DESCRIPTION
**Pull request by jadnco**

### CODE REVIEW

**Comment by jadnco** [comment]
@lelandrichardson @christopherdro Any chance on getting this merged in? :)

**Comment by christopherdro** [comment]
@jadnco Sorry for the late response, will check on that tonight?

**Comment by christopherdro** [comment]
@jadnco Looks good. Could you squash your commits before we merge this in?

**Comment by lelandrichardson** [comment]
@jadnco what is the meaning of the center coordinate of the region when tilt is enabled?

**Comment by jadnco** [comment]
@lelandrichardson Nothing would change from what it already means. Tilt only changes when users start interacting with the map (swiping up/down with two fingers). That feature is already enabled by default, so adding the `pitchEnabled` property just allows developers to disable it.

Does that answer the question?

**Comment by christopherdro** [comment]
👍 Thank you.

**Comment by mbmelgo** [comment]
how to set the pitch of the map when the map was loaded?

**Pull request merged**
