### PR TITLE
Fixes example JS code for RN 29 compatibility

### PR DESCRIPTION
**Pull request by felipecsl**
Also bump to RN to 30-rc

### CODE REVIEW

**Comment by felipecsl** [comment]
I think it wasn't working with RN 29 either

**Comment by lelandrichardson** [comment]
we probably shouldn't use 0.30 until it's out of RC, no?

**Comment by felipecsl** [comment]
yeah I agree. I'll rollback to 0.29.1

**Comment by felipecsl** [comment]
alright bumped down to 29.2, can I get a quick stamp, @lelandrichardson, @christopherdro ?

**Pull request merged**
