### PR TITLE
Resolve #371

### LINKED ISSUE #371: RN 0.29 ios header issue
should we change
AIRMap.h   line 12
#import "React/RCTComponent.h"

AIRMapCallout.h  line 7
#import "React/RCTView.h"

to dir Views ?

### PR DESCRIPTION
**Pull request by kfiroo**
As @nascode suggested this resolved the iOS build errors for me

### CODE REVIEW

**Comment by lelandrichardson** [comment]
Hmm. Will this then break it again for users using Cocoapods, then?  IIRC The opposite changes were just made to support cocoapods.

**Comment by kfiroo** [comment]
@lelandrichardson oh, I didn't realise it will break the Cocoapods users, sorry.

I'm not familiar with iOS development, is there a correct way of doing this?

**Comment by npomfret** [comment]
Is there a solution yet?  Trying to upgrade to RN0.29 and this is my only blocker - br great to get it fixed

**Comment by kfiroo** [comment]
@npomfret you can use my fork for now if you need.

**Comment by lelandrichardson** [comment]
@kfiroo i'm trying to figure out how to do this correctly for both cocoapods and library setups. If anyone knows, I would really appreciate some help :/

**Comment by kfiroo** [comment]
@lelandrichardson Sorry bro, no idea :(

**Comment by ariellephan** [comment]
I believe @kfiroo fix is better practice. To reference the correct path, cocoapods users can try this in the Podfile

`pod 'React', :path => 'node_modules/react-native'`
`pod 'React/RCTGeolocation', :path => 'node_modules/react-native'`

**Comment by kfiroo** [comment]
@ariellephan Thank for the ref.
@lelandrichardson Any news about this?

**Comment by lelandrichardson** [comment]
@kfiroo I think we need to make sure the entire library references these files with `#import <Foo.h>` instead of `#import "Foo.h"`. I'm not 100% sure though. Can you try this and verify that it works for your setup? Then I can verify it's not broken for cocoapods users.

**Comment by kfiroo** [comment]
@lelandrichardson Cool! I'll try and let you know.

**Comment by christopherdro** [comment]
@lelandrichardson These changes are specific to RN 0.30

Related #411

**Comment by kfiroo** [comment]
Hey @lelandrichardson  
So I wanted to tryout your suggestion but I see we already use `#import <Foo.h>` what do you think?

Also I see we import `RCTComponent .h` twice in (AIRMap.h#L12-L15)[https://github.com/lelandrichardson/react-native-maps/blob/master/ios/AirMaps/AIRMap.h#L12-L15]  
Should we try removing one?

**Comment by kfiroo** [comment]
Master caught up with this

**Pull request closed without merging**
